# Generated by Django 4.0.3 on 2022-06-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='DateF',
            field=models.DateField(auto_now=True),
        ),
    ]
