# Generated by Django 4.0.3 on 2022-06-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_usermodel_datef'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='TimeF',
            field=models.TimeField(auto_now=True),
        ),
    ]
